# fly.toml app configuration file generated for garage-floral-field-9662 on 2024-07-15T09:29:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'garage-floral-field-9662'
primary_region = 'ewr'

[build]
  [build.args]
    GO_VERSION = '1.21.5'

[env]
  PORT = '8080'
  BASE_URL= 'https://garage-floral-field-9662.fly.dev'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
