// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Steve Landry Tene",
            "email": "steve.landry@cloudpit.ca"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/appointments": {
            "get": {
                "description": "find all appointments",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "appointment"
                ],
                "summary": "find all appointments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/appointment.Appointment"
                            }
                        }
                    }
                }
            }
        },
        "/companies": {
            "get": {
                "description": "find all companies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "find all companies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/company.Company"
                            }
                        }
                    }
                }
            }
        },
        "/companies/{id}": {
            "get": {
                "description": "find by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "find by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the user to create",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/company.Company"
                        }
                    }
                }
            }
        },
        "/operations": {
            "get": {
                "description": "find all garage operations",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "operation"
                ],
                "summary": "find all garage operations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/operation.ServiceOperation"
                            }
                        }
                    }
                }
            }
        },
        "/service-requests": {
            "get": {
                "description": "find all services requests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service request"
                ],
                "summary": "find all service requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/servicerequest.ServiceRequest"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "find all users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "find all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/user.User"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "create user",
                "parameters": [
                    {
                        "description": "the user to create",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserCreate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "find user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "find user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    }
                }
            },
            "put": {
                "description": "update user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "update user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the user to update",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserUpdate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/vehicles": {
            "get": {
                "description": "find all vehicles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vehicle"
                ],
                "summary": "find all vehicles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/vehicle.Vehicle"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "appointment.Appointment": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "customer_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location_id": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "company.Company": {
            "type": "object",
            "properties": {
                "address_line_1": {
                    "type": "string"
                },
                "address_line_2": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "core.LocalizedMessage": {
            "type": "object",
            "additionalProperties": {
                "type": "string"
            }
        },
        "operation.Operation": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "description": {
                    "$ref": "#/definitions/core.LocalizedMessage"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/core.LocalizedMessage"
                },
                "service_operation_id": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "operation.ServiceOperation": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "$ref": "#/definitions/core.LocalizedMessage"
                },
                "operations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/operation.Operation"
                    }
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "servicerequest.ServiceRequest": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                }
            }
        },
        "user.UserCreate": {
            "description": "UserCreate information with user firstname and lastname",
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@doe.com"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "john"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "doe"
                }
            }
        },
        "user.UserUpdate": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@doe.com"
                },
                "first_name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "john"
                },
                "last_name": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 2,
                    "example": "doe"
                }
            }
        },
        "vehicle.Vehicle": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Automatically managed by GORM for creation time",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "make": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Automatically managed by GORM for update time",
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
