basePath: /
info:
  contact: {}
paths:
  /companies:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: find all users
      tags:
      - example
  /users:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: find all users
      tags:
      - example
swagger: "2.0"
