basePath: /
definitions:
  company.Company:
    properties:
      address_line_1:
        type: string
      address_line_2:
        type: string
      name:
        type: string
    type: object
  user.User:
    properties:
      first_name:
        type: string
      last_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /companies:
    get:
      consumes:
      - application/json
      description: find all companies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/company.Company'
      summary: find all companies
      tags:
      - company
  /users:
    get:
      consumes:
      - application/json
      description: find all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
      summary: find all users
      tags:
      - user
swagger: "2.0"
